# Generated by Django 4.2.25 on 2025-12-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True, verbose_name="Code")),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Description detaillee")),
                (
                    "source_app_label",
                    models.CharField(max_length=120, verbose_name="Application source"),
                ),
                ("source_model", models.CharField(max_length=120, verbose_name="Modele source")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("model", "Modele Django"),
                            ("sql", "SQL"),
                            ("graphql", "GraphQL"),
                            ("python", "Python"),
                        ],
                        default="model",
                        max_length=30,
                        verbose_name="Type de source",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=list,
                        help_text="Liste de filtres {field, lookup, value}.",
                        verbose_name="Filtres par defaut",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=list,
                        help_text="Colonnes pour regroupements/axes.",
                        verbose_name="Dimensions",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=list,
                        help_text="Agregations (sum, avg, count...).",
                        verbose_name="Mesures",
                    ),
                ),
                (
                    "computed_fields",
                    models.JSONField(
                        default=list,
                        help_text="Formules basees sur dimensions/mesures.",
                        verbose_name="Champs calcules",
                    ),
                ),
                (
                    "ordering",
                    models.JSONField(
                        default=list,
                        help_text="Expressions order_by appliquees lors des executions.",
                        verbose_name="Tri par defaut",
                    ),
                ),
                (
                    "preview_limit",
                    models.PositiveIntegerField(default=50, verbose_name="Limite apercu"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Sections, quick fields, champs favorises.",
                        verbose_name="Metadonnees UI",
                    ),
                ),
                (
                    "last_materialized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Derniere materialisation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mise a jour")),
            ],
            options={
                "verbose_name": "Jeu de donnees BI",
                "verbose_name_plural": "Jeux de donnees BI",
                "ordering": ["title", "code"],
                "permissions": [
                    ("run_dataset_preview", "Peut executer un apercu de dataset"),
                    ("materialize_dataset", "Peut materialiser un dataset"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True, verbose_name="Code")),
                ("title", models.CharField(max_length=140, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "layout",
                    models.JSONField(
                        default=list,
                        help_text="Disposition des visualisations {visualization_id, position}.",
                        verbose_name="Layout",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=list,
                        help_text="Filtres globaux appliques a toutes les visualisations.",
                        verbose_name="Filtres applicables",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, default="light", max_length=60, verbose_name="Theme"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mise a jour")),
            ],
            options={
                "verbose_name": "Rapport BI",
                "verbose_name_plural": "Rapports BI",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ReportingVisualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=80, verbose_name="Code")),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("table", "Tableau"),
                            ("bar", "Histogramme"),
                            ("line", "Courbe"),
                            ("pie", "Camembert"),
                            ("kpi", "Indicateur"),
                            ("area", "Aire"),
                            ("pivot", "Pivot"),
                            ("heatmap", "Heatmap"),
                            ("pdf", "Export PDF"),
                        ],
                        default="table",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Axes, colonnes, legende, couleurs.",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        default=list,
                        help_text="Filtres appliques avant l execution.",
                        verbose_name="Filtres par defaut",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=dict,
                        help_text="Preferences de rendu (theme, animations).",
                        verbose_name="Options UI",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Visualisation par defaut"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mise a jour")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="rail_django_graphql.reportingdataset",
                        verbose_name="Jeu de donnees",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualisation BI",
                "verbose_name_plural": "Visualisations BI",
                "ordering": ["dataset__title", "title"],
                "unique_together": {("dataset", "code")},
            },
        ),
        migrations.CreateModel(
            name="ReportingReportBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1, verbose_name="Position")),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text="Coordonnees (x,y,width,height) pour le frontend.",
                        verbose_name="Layout",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(blank=True, max_length=140, verbose_name="Titre alternatif"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="rail_django_graphql.reportingreport",
                        verbose_name="Rapport",
                    ),
                ),
                (
                    "visualization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="rail_django_graphql.reportingvisualization",
                        verbose_name="Visualisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloc de rapport",
                "verbose_name_plural": "Blocs de rapport",
                "ordering": ["position"],
                "unique_together": {("report", "visualization")},
            },
        ),
        migrations.AddField(
            model_name="reportingreport",
            name="visualizations",
            field=models.ManyToManyField(
                related_name="reports",
                through="rail_django_graphql.ReportingReportBlock",
                to="rail_django_graphql.reportingvisualization",
                verbose_name="Visualisations",
            ),
        ),
        migrations.CreateModel(
            name="ReportingExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Titre")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("xlsx", "Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Termine"),
                            ("failed", "Echec"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="Filtres appliques lors de l export.",
                        verbose_name="Filtres",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot utilise par le frontend (donnees et layout).",
                        verbose_name="Payload",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Erreur")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Debut")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Fin")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation")),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="rail_django_graphql.reportingdataset",
                        verbose_name="Dataset",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="rail_django_graphql.reportingreport",
                        verbose_name="Rapport",
                    ),
                ),
                (
                    "visualization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="rail_django_graphql.reportingvisualization",
                        verbose_name="Visualisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export BI",
                "verbose_name_plural": "Exports BI",
                "ordering": ["-created_at"],
            },
        ),
    ]
