// AI-GENERATED: Review required
// Generated by: Assistant on 2025-11-12
// Purpose: Reusable GraphQL mutation builders and related TypeScript types
// Context: Aligned to rail_django_graphql MutationGenerator outputs

/*
"""
Purpose: Provide TypeScript types and helper functions to generate GraphQL mutations
         (create, update, delete, bulk operations, and method mutations) based on
         rail_django_graphql generators. These builders produce mutation documents
         using the naming conventions from MutationGenerator.generate_all_mutations.

Args:
    model_name (string): Django model class name (e.g., "BlogPost", "Category").
    object_selection (string): GraphQL selection set for the returned object(s). Defaults to "id".
    method_name (string): For method mutations, the model method name (e.g., "publish").
    options (object): Optional configuration for method mutation builder.

Returns:
    string: GraphQL mutation document string ready for use with GraphQL clients.
    Types: Generic TypeScript types for variables and results of each mutation pattern.

Raises:
    None directly. GraphQL execution may return structured errors (see MutationError).

Example:
    >>> const doc = build_create_mutation("BlogPost", "id title status");
    >>> // Send `doc` with variables: { input: { title: "Hello", status: "PUBLISHED" } }
"""
*/

/**
 * Common JSON value type used for flexible input payloads.
 */
export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/**
 * Structured error returned by server mutations (matches MutationError in Python).
 */
export type MutationError = {
  field?: string | null;
  message: string;
};

/**
 * Generic response wrapper types for standard mutations.
 */
export type CreateMutationResponse<TModel> = {
  ok: boolean;
  object: TModel | null;
  errors: MutationError[] | null;
};

export type UpdateMutationResponse<TModel> = {
  ok: boolean;
  object: TModel | null;
  errors: MutationError[] | null;
};

export type DeleteMutationResponse<TModel> = {
  ok: boolean;
  object: TModel | null;
  errors: MutationError[] | null;
};

export type BulkCreateMutationResponse<TModel> = {
  ok: boolean;
  objects: TModel[];
  errors: MutationError[] | null;
};

export type BulkUpdateMutationResponse<TModel> = {
  ok: boolean;
  objects: TModel[];
  errors: MutationError[] | null;
};

export type BulkDeleteMutationResponse<TModel> = {
  ok: boolean;
  objects: TModel[];
  errors: MutationError[] | null;
};

export type MethodMutationResponse<TResult> = {
  ok: boolean;
  result: TResult | null;
  errors: MutationError[] | null;
};

/**
 * Variable wrapper types matching server-side mutation argument shapes.
 */
export type CreateMutationVariables<TCreateInput extends Record<string, JsonValue>> = {
  input: TCreateInput;
};

export type UpdateMutationVariables<TUpdateInput extends Record<string, JsonValue>> = {
  id: string;
  input: TUpdateInput;
};

export type BulkCreateMutationVariables<TCreateInput extends Record<string, JsonValue>> = {
  inputs: TCreateInput[];
};

export type BulkUpdateItem<TUpdateInput extends Record<string, JsonValue>> = {
  id: string;
  data: TUpdateInput;
};

export type BulkUpdateMutationVariables<TUpdateInput extends Record<string, JsonValue>> = {
  inputs: BulkUpdateItem<TUpdateInput>[];
};

export type BulkDeleteMutationVariables = {
  ids: string[];
};

export type MethodMutationVariables<TInput extends Record<string, JsonValue> | undefined = undefined> = (
  TInput extends Record<string, JsonValue>
    ? { id: string; input: TInput }
    : { id: string }
);

/**
 * Helper: normalize a model name to PascalCase (e.g., "blog_post" -> "BlogPost").
 */
function to_pascal_case(model_name: string): string {
  const has_upper = /[A-Z]/.test(model_name);
  if (has_upper && !model_name.includes('_')) {
    return model_name;
  }
  return model_name
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

/**
 * Helper: build mutation field suffix in snake_case from model name.
 * Examples: BlogPost -> "blog_post", blog_post -> "blog_post"
 */
function to_field_suffix(model_name: string): string {
  const pascal = to_pascal_case(model_name);
  const snake = pascal
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
  return snake.replace(/[^a-z0-9_]+/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
}

/**
 * Helper: GraphQL input type names derived from server convention.
 */
function get_create_input_type_name(model_name: string): string {
  return `Create${to_pascal_case(model_name)}Input`;
}

function get_update_input_type_name(model_name: string): string {
  return `Update${to_pascal_case(model_name)}Input`;
}

/**
"""
Purpose: Build GraphQL mutation for creating a model instance.
Args:
    model_name: Django model class name (PascalCase or snake_case).
    object_selection: GraphQL selection set for the returned object. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_create_mutation("BlogPost", "id title status")
"""
 */
export function build_create_mutation(model_name: string, object_selection = 'id'): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const input_type = get_create_input_type_name(model_name);
  const operation_name = `Create${pascal}`;
  return (
    `mutation ${operation_name}($input: ${input_type}!) {\n` +
    `  create_${suffix}(input: $input) {\n` +
    `    ok\n` +
    `    object { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/**
"""
Purpose: Build GraphQL mutation for updating an existing model instance.
Args:
    model_name: Django model class name.
    object_selection: GraphQL selection set for the returned object. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_update_mutation("BlogPost", "id title status")
"""
 */
export function build_update_mutation(model_name: string, object_selection = 'id'): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const input_type = get_update_input_type_name(model_name);
  const operation_name = `Update${pascal}`;
  return (
    `mutation ${operation_name}($id: ID!, $input: ${input_type}!) {\n` +
    `  update_${suffix}(id: $id, input: $input) {\n` +
    `    ok\n` +
    `    object { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/**
"""
Purpose: Build GraphQL mutation for deleting a model instance.
Args:
    model_name: Django model class name.
    object_selection: Selection for the returned deleted object snapshot. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_delete_mutation("BlogPost")
"""
 */
export function build_delete_mutation(model_name: string, object_selection = 'id'): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const operation_name = `Delete${pascal}`;
  return (
    `mutation ${operation_name}($id: ID!) {\n` +
    `  delete_${suffix}(id: $id) {\n` +
    `    ok\n` +
    `    object { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/**
"""
Purpose: Build GraphQL mutation for bulk creation of model instances.
Args:
    model_name: Django model class name.
    object_selection: GraphQL selection set for each returned object. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_bulk_create_mutation("BlogPost", "id title")
"""
 */
export function build_bulk_create_mutation(model_name: string, object_selection = 'id'): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const input_type = get_create_input_type_name(model_name);
  const operation_name = `BulkCreate${pascal}`;
  return (
    `mutation ${operation_name}($inputs: [${input_type}!]!) {\n` +
    `  bulk_create_${suffix}(inputs: $inputs) {\n` +
    `    ok\n` +
    `    objects { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/**
"""
Purpose: Build GraphQL mutation for bulk update of model instances.
Args:
    model_name: Django model class name.
    object_selection: GraphQL selection set for returned objects. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_bulk_update_mutation("BlogPost", "id title")
"""
 */
export function build_bulk_update_mutation(
  model_name: string,
  object_selection = 'id',
  bulk_input_type_name?: string,
): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  // Note: BulkUpdateInput is defined per-model in server code; name may be global.
  const bulk_input_type = bulk_input_type_name || 'BulkUpdateInput';
  const operation_name = `BulkUpdate${pascal}`;
  return (
    `mutation ${operation_name}($inputs: [${bulk_input_type}!]!) {\n` +
    `  bulk_update_${suffix}(inputs: $inputs) {\n` +
    `    ok\n` +
    `    objects { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/**
"""
Purpose: Build GraphQL mutation for bulk deletion of model instances.
Args:
    model_name: Django model class name.
    object_selection: Selection for returned deleted objects. Defaults to "id".
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_bulk_delete_mutation("BlogPost", "id")
"""
 */
export function build_bulk_delete_mutation(model_name: string, object_selection = 'id'): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const operation_name = `BulkDelete${pascal}`;
  return (
    `mutation ${operation_name}($ids: [ID!]!) {\n` +
    `  bulk_delete_${suffix}(ids: $ids) {\n` +
    `    ok\n` +
    `    objects { ${object_selection} }\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

export type MethodMutationBuilderOptions = {
  include_input?: boolean;
  input_type_name?: string;
  result_selection?: string; // For object results; omit for scalar results
};

/**
"""
Purpose: Build GraphQL mutation for executing a model method mutation.
Args:
    model_name: Django model class name.
    method_name: The model method name used to generate the mutation field.
    options: Optional builder configuration (input presence, input type, result selection).
Returns:
    string: GraphQL mutation document.
Raises:
    None
Example:
    >>> build_method_mutation("BlogPost", "publish", { include_input: false })
"""
 */
export function build_method_mutation(
  model_name: string,
  method_name: string,
  options: MethodMutationBuilderOptions = {},
): string {
  const pascal = to_pascal_case(model_name);
  const suffix = to_field_suffix(model_name);
  const operation_name = `${pascal}${method_name.charAt(0).toUpperCase()}${method_name.slice(1)}`;
  const include_input = options.include_input === true;
  const input_type_name = options.input_type_name || `${pascal}${method_name.charAt(0).toUpperCase()}${method_name.slice(1)}Input`;
  const has_object_result = typeof options.result_selection === 'string' && options.result_selection.trim().length > 0;

  const var_defs = include_input ? `($id: ID!, $input: ${input_type_name}!)` : `($id: ID!)`;
  const arg_defs = include_input ? `(id: $id, input: $input)` : `(id: $id)`;
  const result_block = has_object_result ? `result { ${options.result_selection} }` : `result`;

  return (
    `mutation ${operation_name}${var_defs} {\n` +
    `  ${suffix}_${method_name}${arg_defs} {\n` +
    `    ok\n` +
    `    ${result_block}\n` +
    `    errors { field message }\n` +
    `  }\n` +
    `}`
  );
}

/*
"""
Purpose: Usage examples for common clients (graphql-request, Apollo).
Args: None
Returns: None
Raises: None
Example:
    // graphql-request
    import { GraphQLClient } from 'graphql-request';
    const client = new GraphQLClient('/graphql');
    const mutation = build_create_mutation('BlogPost', 'id title status');
    const variables: CreateMutationVariables<{ title: string; status: string }> = {
      input: { title: 'Hello', status: 'PUBLISHED' },
    };
    const data = await client.request<{ create_blog_post: CreateMutationResponse<{ id: string; title: string; status: string }> }>(
      mutation,
      variables,
    );

    // Apollo Client (string documents or gql tagged template)
    import { useMutation, gql } from '@apollo/client';
    const CREATE_DOC = gql`${build_create_mutation('Category', 'id name')}`;
    const [mutate] = useMutation(CREATE_DOC);
    await mutate<{ create_category: CreateMutationResponse<{ id: string; name: string }> }, CreateMutationVariables<{ name: string }>>({
      variables: { input: { name: 'Tools' } },
    });
"""
*/