# Generated by Django 4.2.24 on 2025-09-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_client_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="comments",
                to="test_app.tag",
                verbose_name="Étiquettes",
            ),
        ),
    ]
