# Generated by Django 4.2.13 on 2025-09-27 22:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_app", "0004_comment_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                ("avatar", models.URLField(blank=True, verbose_name="Avatar")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profils",
            },
        ),
        migrations.RemoveField(
            model_name="bill",
            name="client",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="test_app_po_created_4b9457_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="test_app_po_status_a6a05d_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="order",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="client",
            name="charfield",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="featured_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="post",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="post",
            name="related_posts",
        ),
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.AddField(
            model_name="client",
            name="raison",
            field=models.CharField(default="dsd", max_length=255, verbose_name="Nom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="Couleur"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 9, 27, 22, 15, 59, 505732, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom de la catégorie"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approuvé"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="test_app.post",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="test_app.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="test_app.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publié le"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("archived", "Archivé"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="test_app.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nom du tag"
            ),
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
