# Generated by Django 4.2.24 on 2025-09-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0005_profile_remove_bill_client_alter_category_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse", models.CharField(max_length=255, verbose_name="Adresse")),
                ("ville", models.CharField(max_length=255, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                ("pays", models.CharField(max_length=255, verbose_name="Pays")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="test_app.client",
                        verbose_name="Client",
                    ),
                ),
            ],
        ),
    ]
