# Generated by Django 4.2.24 on 2025-09-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0006_clientinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientinformation",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="test_app.client",
                verbose_name="Client",
            ),
        ),
    ]
