# Generated by Django 4.2.24 on 2025-09-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("test_app", "0009_alter_post_options_remove_post_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalClient",
            fields=[
                (
                    "client_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_app.client",
                    ),
                ),
                ("test", models.CharField(max_length=255, verbose_name="Nom")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("test_app.client",),
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="client",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
