# Generated by Django 4.2.24 on 2025-09-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0010_localclient_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.RemoveField(
            model_name="client",
            name="polymorphic_ctype",
        ),
        migrations.DeleteModel(
            name="LocalClient",
        ),
    ]
