"""
Django settings for django_graphql_auto project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6uzw8)g9j8+vfow(c#+wlhwi^_r8+x0n-or$-^atg@q&#x()0n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "graphene_django",
    "django_filters",
    "corsheaders",
    # Local apps
    "django_graphql_auto",
    "django_graphql_auto.core",
    "django_graphql_auto.generators",
    "django_graphql_auto.extensions",
    "test_app",
    "tests",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "cache_middleware.GraphQLCacheInvalidationMiddleware",  # Cache invalidation middleware
]

ROOT_URLCONF = "django_graphql_auto.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_graphql_auto.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# GraphQL settings
GRAPHENE = {
    'SCHEMA': 'django_graphql_auto.schema.schema',
    'SCHEMA_OUTPUT': 'schema.graphql',  # Optional: output the schema in SDL format
    'SCHEMA_INDENT': 2,  # Optional: pretty formatting for schema output
    'MIDDLEWARE': [
        'graphene_django.debug.DjangoDebugMiddleware',
    ],
    'CAMELCASE_ERRORS': False,  # Keep error messages in snake_case
    'ATOMIC_MUTATIONS': True,  # Wrap mutations in transactions
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_graphql_auto': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
            
        },
    },
}

DJANGO_GRAPHQL_AUTO = {
    # ========================================
    # CONFIGURATION GÉNÉRALE DU SCHÉMA
    # ========================================
    
    # Répertoire de sortie pour les schémas générés
    'SCHEMA_OUTPUT_DIR': 'generated_schema/',
    
    # Génération automatique du schéma GraphQL
    'AUTO_GENERATE_SCHEMA': True,
    
    # Convention de nommage pour les champs GraphQL (snake_case, camelCase)
    'NAMING_CONVENTION': 'snake_case',
    
    # Activer l'introspection GraphQL (utile pour le développement)
    'ENABLE_INTROSPECTION': True,
    
    # Activer l'interface GraphiQL/Playground
    'ENABLE_PLAYGROUND': DEBUG,
    
    # Mode debug pour des messages d'erreur détaillés
    'DEBUG_MODE': True,
    
    # Messages d'erreur verbeux
    'VERBOSE_ERRORS': True,
    
    # ========================================
    # INCLUSION/EXCLUSION DES MODÈLES
    # ========================================
    
    # Applications à inclure (vide = toutes les applications)
    'APPS_TO_INCLUDE': [],
    
    # Applications à exclure de la génération du schéma
    'APPS_TO_EXCLUDE': ['admin', 'auth', 'contenttypes', 'sessions'],
    
    # Modèles spécifiques à exclure
    'MODELS_TO_EXCLUDE': ['LogEntry', 'Session'],
    
    # ========================================
    # FONCTIONNALITÉS PRINCIPALES
    # ========================================
    
    # Activer les mutations GraphQL
    'ENABLE_MUTATIONS': True,
    
    # Activer les abonnements GraphQL (subscriptions)
    'ENABLE_SUBSCRIPTIONS': False,
    
    # Activer le système de filtrage avancé
    'ENABLE_FILTERS': True,
    
    # Activer les opérations imbriquées (nested operations)
    'ENABLE_NESTED_OPERATIONS': True,
    
    # Activer le téléchargement de fichiers
    'ENABLE_FILE_UPLOADS': True,
    
    # Activer les scalaires personnalisés
    'ENABLE_CUSTOM_SCALARS': True,
    
    # Activer la prise en charge de l'héritage de modèles
    'ENABLE_INHERITANCE': True,
    
    # ========================================
    # CONFIGURATION DES REQUÊTES
    # ========================================
    
    'QUERY_SETTINGS': {
        # Utiliser les connexions Relay pour la pagination
        'use_relay': False,
        
        # Activer la génération de filtres pour les requêtes
        'generate_filters': True,
        
        # Activer le tri des résultats
        'generate_ordering': True,
        
        # Activer la pagination
        'generate_pagination': True,
        'enable_pagination': True,
        
        # Activer le tri (alias pour generate_ordering)
        'enable_ordering': True,
        
        # Taille de page par défaut pour la pagination
        'default_page_size': 20,
        
        # Taille de page maximale autorisée
        'max_page_size': 100,
        
        # Champs de recherche supplémentaires par modèle
        'additional_lookup_fields': {
            # 'Post': ['slug', 'uuid'],
            # 'User': ['username', 'email'],
        },
    },
    
    # ========================================
    # CONFIGURATION DES MUTATIONS
    # ========================================
    
    'MUTATION_SETTINGS': {
        # Activer les mutations de création
        'generate_create': True,
        'enable_create': True,
        
        # Activer les mutations de mise à jour
        'generate_update': True,
        'enable_update': True,
        
        # Activer les mutations de suppression
        'generate_delete': True,
        'enable_delete': True,
        
        # Activer les opérations en lot (bulk operations)
        'generate_bulk': True,
        'enable_bulk_operations': True,
        
        # Activer les mutations de méthodes personnalisées
        'enable_method_mutations': True,
        
        # Préfixe pour les noms de mutations de méthodes
        'method_mutation_prefix': '',
        
        # Inclure les méthodes privées (commençant par _)
        'include_private_methods': False,
        
        # Taille de lot maximale pour les opérations en lot
        'bulk_batch_size': 100,
        
        # Nombre maximum d'objets par opération en lot
        'bulk_max_objects': 1000,
        
        # Timeout des transactions en lot (en secondes)
        'bulk_transaction_timeout': 30,
        
        # Limitation du taux pour les opérations en lot
        'bulk_rate_limit': {
            'max_operations_per_minute': 10,
            'max_objects_per_hour': 10000,
        },
        
        # Champs requis pour les opérations de mise à jour par modèle
        'required_update_fields': {
            # 'Post': ['title'],
            # 'User': ['email'],
        },
        
        # ========================================
        # RELATIONS IMBRIQUÉES (NESTED RELATIONS)
        # ========================================
        
        # Contrôle global des relations imbriquées
        'enable_nested_relations': True,
        
        # Configuration par modèle des relations imbriquées
        'nested_relations_config': {
            # 'Post': True,     # Activer pour le modèle Post
            # 'Comment': False, # Désactiver pour le modèle Comment
            # 'User': True,     # Activer pour le modèle User
        },
        
        # Configuration granulaire par champ des relations imbriquées
        'nested_field_config': {
            "Post": {
                "category": True,        # Activer les opérations imbriquées pour category
                # "comments": False,     # Désactiver les commentaires imbriqués
                # "related_posts": True, # Activer les posts liés imbriqués
                # "tags": True,          # Activer les tags imbriqués
                # "author": False,       # Désactiver les mises à jour d'auteur imbriquées
            },
            # "Comment": {
            #     "replies": False,      # Désactiver les réponses imbriquées
            # },
        },
    },
    
    # ========================================
    # CONFIGURATION DES TYPES
    # ========================================
    
    'TYPE_SETTINGS': {
        # Champs à exclure par modèle
        'exclude_fields': {
            # 'User': ['password', 'last_login'],
            # 'Post': ['internal_notes'],
        },
        
        # Alias pour exclude_fields
        'excluded_fields': {
            # 'User': ['password_hash'],
        },
        
        # Champs à inclure par modèle (si None, inclure tous les champs non exclus)
        'include_fields': {
            # 'User': ['id', 'username', 'email', 'first_name', 'last_name'],
        },
        
        # Mappages de types de champs personnalisés
        'custom_field_mappings': {
            # 'JSONField': 'graphene.JSONString',
        },
        
        # Activer la génération de filtres pour les types
        'generate_filters': True,
        'enable_filtering': True,
        
        # Activer la conversion automatique en camelCase
        'auto_camelcase': False,
        
        # Activer les descriptions de champs
        'generate_descriptions': True,
    },
    
    # ========================================
    # CONFIGURATION DU FILTRAGE
    # ========================================
    
    'FILTERING': {
        # Activer le système de filtrage
        'ENABLE_FILTERS': True,
        
        # Opérateurs de filtre par défaut par type de champ
        'DEFAULT_FILTER_OPERATORS': {
            'CharField': ['exact', 'icontains', 'startswith', 'endswith', 'iexact', 'contains', 'istartswith', 'iendswith', 'regex', 'iregex', 'in', 'isnull'],
            'TextField': ['exact', 'icontains', 'startswith', 'endswith', 'iexact', 'contains', 'istartswith', 'iendswith', 'regex', 'iregex', 'in', 'isnull'],
            'IntegerField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'in', 'isnull'],
            'FloatField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'in', 'isnull'],
            'DecimalField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'in', 'isnull'],
            'BooleanField': ['exact', 'isnull'],
            'DateTimeField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'date', 'year', 'month', 'day', 'week', 'week_day', 'quarter', 'time', 'hour', 'minute', 'second', 'isnull'],
            'DateField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'year', 'month', 'day', 'week', 'week_day', 'quarter', 'isnull'],
            'TimeField': ['exact', 'gt', 'gte', 'lt', 'lte', 'range', 'hour', 'minute', 'second', 'isnull'],
        },
        
        # Activer les opérateurs logiques (AND, OR, NOT)
        'ENABLE_LOGICAL_OPERATORS': True,
        
        # Activer le filtrage sur les relations
        'ENABLE_RELATIONSHIP_FILTERS': True,
        
        # Profondeur maximale pour le filtrage sur les relations
        'MAX_FILTER_DEPTH': 3,
        
        # Activer les filtres personnalisés
        'ENABLE_CUSTOM_FILTERS': True,
        
        # Filtres personnalisés par modèle
        'CUSTOM_FILTERS': {
            # 'Post': 'myapp.filters.PostFilterSet',
        },
        
        # Activer la mise en cache des filtres
        'ENABLE_FILTER_CACHING': True,
        
        # Timeout du cache des filtres (en secondes)
        'FILTER_CACHE_TIMEOUT': 300,
        
        # Préfixe des clés de cache pour les filtres
        'FILTER_CACHE_KEY_PREFIX': 'graphql_filter',
    },
    
    # ========================================
    # CONFIGURATION DE LA PAGINATION
    # ========================================
    
    'PAGINATION': {
        # Taille de page par défaut
        'PAGINATION_SIZE': 20,
        'DEFAULT_PAGE_SIZE': 20,
        
        # Taille de page maximale
        'MAX_PAGE_SIZE': 100,
        
        # Activer la pagination Relay
        'USE_RELAY_PAGINATION': False,
        
        # Activer la pagination par curseur
        'ENABLE_CURSOR_PAGINATION': True,
        
        # Activer la pagination par offset
        'ENABLE_OFFSET_PAGINATION': True,
    },
    
    # ========================================
    # SÉCURITÉ ET PERMISSIONS
    # ========================================
    
    'SECURITY': {
        # Profondeur maximale des requêtes (protection contre les attaques de profondeur)
        'MAX_QUERY_DEPTH': 10,
        
        # Complexité maximale des requêtes
        'MAX_QUERY_COMPLEXITY': 1000,
        
        # Activer l'analyse du coût des requêtes
        'QUERY_COST_ANALYSIS': True,
        
        # Timeout des requêtes (en secondes)
        'QUERY_TIMEOUT': 30,
        
        # Permissions pour les mutations
        'MUTATION_PERMISSIONS': {
            # 'create': 'django_graphql_auto.permissions.IsAuthenticated',
            # 'update': 'django_graphql_auto.permissions.IsOwnerOrReadOnly',
            # 'delete': 'django_graphql_auto.permissions.IsOwnerOrAdmin',
        },
        
        # Champs sensibles à masquer
        'SENSITIVE_FIELDS': {
            # 'User': ['password', 'password_hash', 'secret_key'],
        },
        
        # Permissions pour l'accès aux champs sensibles
        'FIELD_PERMISSIONS': {
            # 'sensitive_field': 'your_app.view_sensitive_data'
        },
    },
    
    # ========================================
    # OPTIMISATION DES PERFORMANCES
    # ========================================
    
    'PERFORMANCE': {
        # Activer l'optimisation des requêtes
        'ENABLE_QUERY_OPTIMIZATION': True,
        
        # Activer la mise en cache des schémas
        'ENABLE_SCHEMA_CACHING': True,
        
        # Timeout du cache des schémas (en secondes)
        'SCHEMA_CACHE_TIMEOUT': 3600,
        
        # Activer le monitoring des performances
        'PERFORMANCE_MONITORING': True,
        
        # Seuil pour les requêtes lentes (en millisecondes)
        'SLOW_QUERY_THRESHOLD': 1000,
        
        # Activer la compression des réponses
        'ENABLE_RESPONSE_COMPRESSION': True,
        
        # Taille de lot pour les opérations en lot par modèle
        'MODEL_SPECIFIC_BATCH_SIZES': {
            # 'LargeModel': 50,   # Modèles volumineux
            # 'SmallModel': 500,  # Modèles légers
        },
    },
    
    # ========================================
    # SCALAIRES ET CONVERTISSEURS PERSONNALISÉS
    # ========================================
    
    'CUSTOM_SCALARS': {
        # Scalaires personnalisés pour les types de champs Django
        # 'JSONField': 'django_graphql_auto.scalars.JSONScalar',
        # 'UUIDField': 'django_graphql_auto.scalars.UUIDScalar',
        # 'EmailField': 'django_graphql_auto.scalars.EmailScalar',
        # 'URLField': 'django_graphql_auto.scalars.URLScalar',
    },
    
    'FIELD_CONVERTERS': {
        # Convertisseurs personnalisés pour les types de champs
        # 'custom_field': 'your_app.converters.CustomFieldConverter',
    },
    
    # ========================================
    # HOOKS ET EXTENSIONS
    # ========================================
    
    'SCHEMA_HOOKS': [
        # Hooks personnalisés pour la génération de schéma
        # 'your_app.hooks.pre_schema_generation',
        # 'your_app.hooks.post_schema_generation',
    ],
    
    'MIDDLEWARE': [
        # Middleware GraphQL personnalisé
        # 'your_app.middleware.CustomGraphQLMiddleware',
    ],
    
    # ========================================
    # OPÉRATIONS IMBRIQUÉES AVANCÉES
    # ========================================
    
    'NESTED_OPERATIONS': {
        # Activer les opérations imbriquées
        'ENABLE_NESTED_CREATE': True,
        'ENABLE_NESTED_UPDATE': True,
        'ENABLE_NESTED_DELETE': True,
        
        # Paramètres de performance
        'BULK_THRESHOLD': 10,
        'MAX_NESTING_DEPTH': 5,
        'ENABLE_QUERY_OPTIMIZATION': True,
        
        # Paramètres de sécurité
        'ENABLE_DELETION_SAFETY_CHECKS': True,
        'DEFAULT_DELETE_PROTECTION': True,
        'REQUIRE_EXPLICIT_CASCADE': True,
        
        # Paramètres de validation
        'ENABLE_NESTED_VALIDATION': True,
        'VALIDATE_RELATIONSHIPS': True,
        'STRICT_TYPE_CHECKING': True,
        
        # Paramètres de transaction
        'USE_TRANSACTIONS': True,
        'TRANSACTION_ISOLATION_LEVEL': 'READ_COMMITTED',
    },
    
    'RELATIONSHIP_HANDLING': {
        # Comportements par défaut pour les relations
        'FOREIGN_KEY_ON_DELETE': 'protect',
        'ONE_TO_MANY_ON_DELETE': 'cascade',
        'MANY_TO_MANY_ON_DELETE': 'clear',
        
        # Comportements de mise à jour
        'FOREIGN_KEY_ON_UPDATE': 'update',
        'ONE_TO_MANY_ON_UPDATE': 'merge',
        'MANY_TO_MANY_ON_UPDATE': 'replace',
    },
    
    # ========================================
    # CONFIGURATION DE DÉVELOPPEMENT/TEST
    # ========================================
    
    'DEVELOPMENT': {
        # Mode test (désactive certaines fonctionnalités coûteuses)
        'TESTING': False,
        
        # Désactiver la mise en cache en développement
        'CACHE_ENABLED': True,
        
        # Taille de page réduite pour les tests
        'TEST_PAGE_SIZE': 5,
        
        # Activer les logs détaillés
        'VERBOSE_LOGGING': True,
        
        # Activer le rechargement automatique du schéma
        'AUTO_RELOAD_SCHEMA': True,
    },
    
    # ========================================
    # INTERNATIONALISATION
    # ========================================
    
    'I18N': {
        # Activer la prise en charge multilingue
        'ENABLE_I18N': True,
        
        # Langues supportées
        'SUPPORTED_LANGUAGES': ['fr', 'en'],
        
        # Langue par défaut
        'DEFAULT_LANGUAGE': 'fr',
        
        # Champs traduisibles par modèle
        'TRANSLATABLE_FIELDS': {
            # 'Post': ['title', 'content', 'description'],
        },
    },
}

