version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-rail_dev}
      POSTGRES_USER: ${POSTGRES_USER:-rail_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: ../..
      dockerfile: django-graphql-boilerplate/deploy/docker/Dockerfile.production
    env_file:
      - ../.env.example
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      DJANGO_DEBUG: "true"
    volumes:
      - ../:/app
      - static_data:/app/static
      - media_data:/app/media
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - static_data:/var/www/static
      - media_data:/var/www/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available/default:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data: