name: Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 3 * * 1" # Weekly Monday UTC 03:00

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
          pip install bandit safety
        working-directory: django-graphql-boilerplate

      - name: Run Bandit security scan
        run: bandit -r . -x tests -q || true
        working-directory: django-graphql-boilerplate

      - name: Run Safety vulnerability check
        run: safety check -r requirements/base.txt || true
        working-directory: django-graphql-boilerplate